### ISSUE TITLE
Error when using this with multiple webpack instances

### ISSUE THREAD

**Issue by naganowl** [jantimon/html-webpack-harddisk-plugin#22]
I ran into an issue with a webpack `4.41.2` upgrade where previously when running multiple webpack processes with `v1.0.1` of this plugin (and `html-webpack-plugin@3.2.0`) that the following error would occur

```
TypeError: HtmlWebpackPlugin.getHooks is not a function
    at /Users/awong/workspace/mavenlink/node_modules/html-webpack-harddisk-plugin/index.js:24:39
    at SyncHook.eval [as call] (eval at create (/Users/awong/workspace/mavenlink/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/Users/awong/workspace/mavenlink/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/awong/workspace/mavenlink/node_modules/webpack/lib/Compiler.js:631:26)
    at hooks.beforeCompile.callAsync.err (/Users/awong/workspace/mavenlink/node_modules/webpack/lib/Compiler.js:667:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/awong/workspace/mavenlink/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/awong/workspace/mavenlink/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/awong/workspace/mavenlink/node_modules/webpack/lib/Compiler.js:662:28)
    at compiler.hooks.watchRun.callAsync.err (/Users/awong/workspace/mavenlink/node_modules/webpack/lib/Watching.js:77:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/awong/workspace/mavenlink/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/awong/workspace/mavenlink/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/Users/awong/workspace/mavenlink/node_modules/webpack/lib/Watching.js:41:32)
    at Watching.compiler.readRecords.err (/Users/awong/workspace/mavenlink/node_modules/webpack/lib/Watching.js:33:9)
    at Compiler.readRecords (/Users/awong/workspace/mavenlink/node_modules/webpack/lib/Compiler.js:529:11)
    at new Watching (/Users/awong/workspace/mavenlink/node_modules/webpack/lib/Watching.js:30:17)
    at Compiler.watch (/Users/awong/workspace/mavenlink/node_modules/webpack/lib/Compiler.js:244:10)

```

Previously, running multiple webpack processes on `3.11` would be just fine with the same plugin versions above.

Perhaps there are still some incompatibilities with this and webpack 4?

**Comment by jantimon** [comment]
Did you add the plugin after the html-webpack-plugin?

**Comment by naganowl** [comment]
I've had `HtmlWebpackHarddiskPlugin` after `HtmlWebpackPlugin` which worked in the webpack 3 case above and fails in the webpack 4 case.

In webpack 4 with `html-webpack-plugin@3.2.0`, having `HtmlWebpackHarddiskPlugin` come first fails immediately with a single webpack process whereas having it come after in the same case has it fail on that error when a second webpack process is running.

**Comment by jantimon** [comment]
works with html-webpack-plugin@4
