### ISSUE TITLE
Issue with output path option

### ISSUE THREAD

**Issue by anvk** [jantimon/html-webpack-harddisk-plugin#7]
From documentation:
```
new HtmlWebpackHarddiskPlugin({
  outputPath: path.resolve(__dirname, 'views')
})
```

If I build my project then everything is fine and `dist/` folder looks properly with a proper `index.html` within (this way I double check that `HtmlWebpackPlugin` config is proper and working). But If I run dev-server, I always receive the same error:

```
Unhandled rejection TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at HtmlWebpackHarddiskPlugin.writeAssetToDisk (/Users/anvk/Documents/myproj/node_modules/html-webpack-harddisk-plugin/index.js:30:23)
    at Compilation.<anonymous> (/Users/anvk/Documents/myproj/node_modules/html-webpack-harddisk-plugin/index.js:16:12)
    at Compilation.applyPluginsAsyncWaterfall (/Users/anvk/Documents/myproj/node_modules/tapable/lib/Tapable.js:86:13)
    at Compilation.tryCatcher (/Users/anvk/Documents/myproj/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/Users/anvk/Documents/myproj/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at /Users/anvk/Documents/myproj/node_modules/html-webpack-plugin/index.js:148:16
    at tryCatcher (/Users/anvk/Documents/myproj/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/anvk/Documents/myproj/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/anvk/Documents/myproj/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/anvk/Documents/myproj/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/anvk/Documents/myproj/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/anvk/Documents/myproj/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/anvk/Documents/myproj/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/anvk/Documents/myproj/node_modules/bluebird/js/release/async.js:17:14)
```

Even though I tried 3 different configs:

1)
```
new HtmlWebpackPlugin({
    filename: '../index.html',
    template: '../../src/templates/index.html',
    inject: true,
    alwaysWriteToDisk: true,
  }),
  new HtmlWebpackHarddiskPlugin({
    outputPath: path.resolve(__dirname, 'dist')
  })
```

2)
```
...

const sourcePath = path.join(__dirname, './src/scripts');
const stylesPath = path.join(__dirname, './src/styles');
const staticsPath = path.join(__dirname, './dist/scripts');
const distPath = path.join(__dirname, './dist');

...

new HtmlWebpackPlugin({
    filename: '../index.html',
    template: '../../src/templates/index.html',
    inject: true,
    alwaysWriteToDisk: true,
  }),
  new HtmlWebpackHarddiskPlugin({
    outputPath: distPath
  })
```

3)

```
new HtmlWebpackPlugin({
    filename: '../index.html',
    template: '../../src/templates/index.html',
    inject: true,
    alwaysWriteToDisk: true,
  }),
  new HtmlWebpackHarddiskPlugin({
    outputPath: './dist'
  })
```

**Comment by CaptEmulation** [comment]
Do you have a full example project you can reference?

**Comment by CaptEmulation** [comment]
I actually don't have a public commit to ref where I am using this (it's in a shared private repo) in a working project.  `webpack.config.js` has this:

```
	new HtmlWebpackPlugin({
		title: 'Widget',
		template: './src/widget.ejs',
		filename: 'widget.ejs',
		alwaysWriteToDisk: true
	}),
	new HtmlHarddiskWebpackPlugin({
		outputPath: path.resolve(__dirname, 'view')
	}),
```

In this case, I am templating a template file to another directory, where it is then served by the express backend.  My devDependencies are thus:

```
    "@captemulation/html-webpack-harddisk-plugin": "^0.1.0",
    "autoprefixer": "^6.5.1",
    "babel-cli": "^6.16.0",
    "babel-core": "^6.17.0",
    "babel-loader": "^6.2.5",
    "babel-plugin-transform-class-properties": "^6.16.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-polyfill": "^6.20.0",
    "babel-preset-es2015": "^6.16.0",
    "babel-preset-es2016": "^6.16.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-0": "^6.16.0",
    "babel-runtime": "^6.11.6",
    "bunyan": "^1.8.5",
    "clean-webpack-plugin": "^0.1.15",
    "cross-spawn": "^5.0.1",
    "css-loader": "^0.25.0",
    "eslint": "^3.8.1",
    "eslint-config-airbnb": "^12.0.0",
    "eslint-plugin-import": "^1.16.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.4.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "gulp": "^3.9.1",
    "gulp-babel": "^6.1.2",
    "gulp-nodemon": "^2.2.1",
    "html-webpack-plugin": "^2.22.0",
    "karma": "^1.4.0",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "node-babel": "^0.1.2",
    "postcss-loader": "^1.0.0",
    "react-hot-loader": "^1.3.1",
    "redux-devtools": "^3.3.1",
    "redux-devtools-dock-monitor": "^1.1.1",
    "redux-devtools-log-monitor": "^1.1.1",
    "run-sequence": "^1.2.2",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.13.2",
    "webpack-cleanup-plugin": "^0.4.1",
    "webpack-dev-middleware": "^1.9.0",
    "webpack-hot-middleware": "^2.15.0"
```

**Comment by anvk** [comment]
Thanks for the reply. I will try to setup some basic project to demonstrate the issue I'm having.

**Comment by anvk** [comment]
@CaptEmulation sorry for the delay.

I managed to create a basic sample of the problem I was describing. My minimal setup is in my public [Git repo](https://github.com/anvk/sample)

Run `npm install` and then `npm start` within to see the issue

**Comment by CaptEmulation** [comment]
OK, I will try it out when I can (tonight at the earliest)

**Comment by anvk** [comment]
Thanks! Take your time. I hope it is not a "simple" user-error which would be embarrassing  :)

**Comment by CaptEmulation** [comment]
I played around with your sample.  The `context` option seems to be mucking stuff up.  I removed the `context` option from the webpack config and adjusted the paths and was able to output a file as expected from a basic webpack build, but `webpack-dev-server` was a little bit more odd....  it was writing out the file but not in the location I expected.  Definitely something squirrely going on here, but you may be able to make it work _sans_ `context` option.

**Comment by anvk** [comment]
Thanks for looking into it. I believe that `context` will stay in the config on our prod app. Maybe this is not a problem with webpack 2.0 Will need to try to switch and see if it makes a difference

**Comment by CaptEmulation** [comment]
Unfortunately I can't.  This was for a client project and I can't share sources.  Also after getting a universal rendering set-up going, and understanding how it works-- I migrated to https://github.com/halt-hammerzeit/react-isomorphic-render which uses `react-hetlmet` under the hood to generate HTML documents on the fly.  No template.  I stopped needing this plugin at that point.
